version: '2'
services:
  app:
    build:
      context: .
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
      - /var/www/node_modules
    environment:
      - NODE_ENV=dev
    command: ["npm", "start"]
